language: ruby
rvm:
- 2.2.1
- 2.2.2
env:
  global:
  - secure: HmDhEi7OoTSYG3Ku09/0KPzPMrEKmlI9wICaFBDtaZp6Rtdp7MAP0i4tlDopEq62ksSjntTGVNITNU3c4jI1UCsHs8Q8ax0MOC7XMf1DXQwZv2sHeCkFq0KpcYVRI85tkscTkYqxrYBTrPaOufZPpesUOIpNXkgZ5rkjD+sp9NY=
  - secure: DGQkSTgkI0daLt5e1MNTBMctaoLgWgF5Y1Db2PXpvpbx6jt1DJ1YFfs+g6PK3bC0fjEu8Mfh4wRV/XbfGNLe2D4PNg+8k+Qei4Iekvthu5L9yJG5MAYUMeqd/0yJJUI5W/FCXBSDt0LnFDmNUOtfDfWAEQ19F4uXHN6+36RQBMM=
